using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Imaging;
using System.Windows.Shell;
using System.Windows.Threading;

namespace LaunchDeck {
  public class MainWindow : Window {
    readonly string _baseDir;readonly CatalogService _catalog;UserSettings _settings;List<AppEntry> _apps=new List<AppEntry>();
    Grid _root,_content;WrapPanel _nav;StackPanel _quick;WrapPanel _cards;TextBox _search;TextBlock _searchHint,_quickCaption,_title,_count,_status,_empty;ScrollViewer _scroll;Button _language;string _selected="ALL";DispatcherTimer _batch;int _batchIndex;List<AppEntry> _pending;
    readonly Brush Bg=new SolidColorBrush(Color.FromRgb(8,13,22)),PanelBg=new SolidColorBrush(Color.FromRgb(14,23,37)),CardBg=new SolidColorBrush(Color.FromRgb(24,37,56)),CardHover=new SolidColorBrush(Color.FromRgb(31,50,73)),TextMain=new SolidColorBrush(Color.FromRgb(239,246,253)),TextMuted=new SolidColorBrush(Color.FromRgb(151,173,194)),Mint=new SolidColorBrush(Color.FromRgb(123,231,201)),Cyan=new SolidColorBrush(Color.FromRgb(71,190,255));

    public MainWindow(string baseDir){
      _baseDir=baseDir;_catalog=new CatalogService(baseDir);_settings=Storage.LoadSettings();Title="LaunchDeck 启界";Width=1280;Height=820;MinWidth=960;MinHeight=650;Background=Bg;Foreground=TextMain;WindowStartupLocation=WindowStartupLocation.CenterScreen;WindowStyle=WindowStyle.None;
      WindowChrome.SetWindowChrome(this,new WindowChrome{CaptionHeight=34,ResizeBorderThickness=new Thickness(7),CornerRadius=new CornerRadius(10),GlassFrameThickness=new Thickness(0),UseAeroCaptionButtons=false});
      try{Icon=BitmapFrame.Create(new Uri(Path.Combine(baseDir,"Assets","LaunchDeck.ico")));}catch{}
      Build();Loaded+=(s,e)=>LoadCatalog();PreviewKeyDown+=OnKeys;
    }

    void Build(){
      _root=new Grid();_root.RowDefinitions.Add(new RowDefinition{Height=new GridLength(34)});_root.RowDefinitions.Add(new RowDefinition{Height=new GridLength(1,GridUnitType.Star)});_root.RowDefinitions.Add(new RowDefinition{Height=new GridLength(34)});Content=_root;
      BuildTitleBar();_content=new Grid{Margin=new Thickness(30,22,24,0)};for(int i=0;i<5;i++)_content.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});_content.RowDefinitions.Add(new RowDefinition{Height=new GridLength(1,GridUnitType.Star)});Grid.SetRow(_content,1);_root.Children.Add(_content);
      BuildHeader();_nav=new WrapPanel{Orientation=Orientation.Horizontal,Margin=new Thickness(-6,16,0,0)};Grid.SetRow(_nav,1);_content.Children.Add(_nav);
      _quickCaption=Text(L.T("quick",_settings.Language),11,FontWeights.Normal,TextMuted);_quickCaption.Margin=new Thickness(0,12,0,8);Grid.SetRow(_quickCaption,2);_content.Children.Add(_quickCaption);
      _quick=new StackPanel{Orientation=Orientation.Horizontal,Margin=new Thickness(0,0,0,24),ClipToBounds=false};Grid.SetRow(_quick,3);_content.Children.Add(_quick);
      var section=new Grid{Margin=new Thickness(0,0,0,12)};section.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});section.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(1,GridUnitType.Star)});_title=Text("",22,FontWeights.SemiBold,TextMain);_count=Text("",12,FontWeights.Normal,TextMuted);_count.VerticalAlignment=VerticalAlignment.Bottom;_count.Margin=new Thickness(16,0,4,3);Grid.SetColumn(_count,1);section.Children.Add(_title);section.Children.Add(_count);Grid.SetRow(section,4);_content.Children.Add(section);
      _cards=new WrapPanel{Orientation=Orientation.Horizontal,ClipToBounds=false};var cardViewport=new Border{Padding=new Thickness(8,0,8,0),ClipToBounds=false,Child=_cards};_scroll=new ScrollViewer{Content=cardViewport,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled};Grid.SetRow(_scroll,5);_content.Children.Add(_scroll);
      _empty=Text("",17,FontWeights.Medium,TextMuted);_empty.HorizontalAlignment=HorizontalAlignment.Center;_empty.VerticalAlignment=VerticalAlignment.Center;_empty.Visibility=Visibility.Collapsed;Grid.SetRow(_empty,5);_content.Children.Add(_empty);
      _status=Text("",11,FontWeights.Normal,TextMuted);_status.Margin=new Thickness(22,0,0,0);_status.VerticalAlignment=VerticalAlignment.Center;Grid.SetRow(_status,2);_root.Children.Add(_status);
      RebuildLabels();
    }

    void BuildTitleBar(){
      var bar=new Grid{Background=new SolidColorBrush(Color.FromRgb(12,19,31))};bar.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(1,GridUnitType.Star)});bar.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});var name=Text("LaunchDeck  启界",11,FontWeights.Medium,TextMuted);name.Margin=new Thickness(15,0,0,0);name.VerticalAlignment=VerticalAlignment.Center;bar.Children.Add(name);
      var controls=new StackPanel{Orientation=Orientation.Horizontal};Grid.SetColumn(controls,1);foreach(var item in new[]{new[]{"−","min"},new[]{"□","max"},new[]{"×","close"}}){var b=FlatButton(item[0],46,34);b.Tag=item[1];WindowChrome.SetIsHitTestVisibleInChrome(b,true);b.Click+=(s,e)=>{var a=(string)((Button)s).Tag;if(a=="min")WindowState=WindowState.Minimized;else if(a=="max")WindowState=WindowState==WindowState.Maximized?WindowState.Normal:WindowState.Maximized;else Close();e.Handled=true;};controls.Children.Add(b);}bar.Children.Add(controls);bar.MouseLeftButtonDown+=(s,e)=>{if(e.OriginalSource is Button)return;if(e.ClickCount==2)WindowState=WindowState==WindowState.Maximized?WindowState.Normal:WindowState.Maximized;else DragMove();};_root.Children.Add(bar);
    }

    void BuildHeader(){
      var header=new Grid();header.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(1,GridUnitType.Star)});header.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(360)});
      var brand=new StackPanel{Orientation=Orientation.Horizontal};try{brand.Children.Add(new Image{Source=IconService.Load(Path.Combine(_baseDir,"Assets","logo.png")),Width=56,Height=56,Margin=new Thickness(0,0,15,0)});}catch{}
      var words=new StackPanel{VerticalAlignment=VerticalAlignment.Center};words.Children.Add(Text("LaunchDeck  启界",27,FontWeights.Bold,TextMain));var tagline=Text(L.T("tag",_settings.Language),12,FontWeights.Normal,TextMuted);tagline.Name="Tagline";words.Children.Add(tagline);brand.Children.Add(words);header.Children.Add(brand);
      var actions=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right,VerticalAlignment=VerticalAlignment.Center};var searchBorder=new Border{Width=212,Height=42,Background=new SolidColorBrush(Color.FromRgb(19,31,49)),BorderBrush=new SolidColorBrush(Color.FromRgb(47,68,92)),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(11),Padding=new Thickness(13,0,10,0)};var searchGrid=new Grid();_search=new TextBox{Background=Brushes.Transparent,BorderThickness=new Thickness(0),Foreground=TextMain,CaretBrush=Mint,FontFamily=new FontFamily("Microsoft YaHei UI, Segoe UI"),FontSize=12,VerticalContentAlignment=VerticalAlignment.Center};_searchHint=Text(L.T("search",_settings.Language),12,FontWeights.Normal,TextMuted);_searchHint.VerticalAlignment=VerticalAlignment.Center;_searchHint.IsHitTestVisible=false;searchGrid.Children.Add(_search);searchGrid.Children.Add(_searchHint);_search.TextChanged+=(s,e)=>{_searchHint.Visibility=_search.Text.Length==0?Visibility.Visible:Visibility.Collapsed;RenderApps(false);};searchBorder.Child=searchGrid;actions.Children.Add(searchBorder);
      _language=SmallButton(L.En(_settings.Language)?"中文":"EN");_language.Click+=(s,e)=>{_settings.Language=L.En(_settings.Language)?"zh-CN":"en-US";Storage.SaveSettings(_settings);RebuildLabels();};actions.Children.Add(_language);
      var refresh=SmallButton("↻");refresh.ToolTip=L.T("refresh",_settings.Language);refresh.Click+=(s,e)=>RefreshAsync();actions.Children.Add(refresh);Grid.SetColumn(actions,1);header.Children.Add(actions);_content.Children.Add(header);
    }

    void RebuildLabels(){
      var tagline=FindNameRecursive<TextBlock>(_root,"Tagline");if(tagline!=null)tagline.Text=L.T("tag",_settings.Language);if(_searchHint!=null)_searchHint.Text=L.T("search",_settings.Language);if(_quickCaption!=null)_quickCaption.Text=L.T("quick",_settings.Language);if(_language!=null)_language.Content=L.En(_settings.Language)?"中文":"EN";BuildNav();RenderQuick();RenderApps(false);
    }

    void BuildNav(){if(_nav==null)return;_nav.Children.Clear();AddNav("ALL",L.T("all",_settings.Language),_apps.Count);AddNav("FAV",L.T("fav",_settings.Language),_apps.Count(a=>_settings.Favorites.Contains(a.Id)));AddNav("RECENT",L.T("recent",_settings.Language),_apps.Count(a=>_settings.Recent.Contains(a.Id)));foreach(var c in CatalogService.Categories)AddNav(c,L.Category(c,_settings.Language),_apps.Count(a=>a.Category==c));}
    void AddNav(string key,string label,int count){var b=FlatButton(label+(count>0?"  "+count:""),Double.NaN,36);b.MinWidth=82;b.Tag=key;b.Margin=new Thickness(6,0,0,6);b.Padding=new Thickness(13,0,13,0);if(_selected==key){b.Background=Mint;b.Foreground=new SolidColorBrush(Color.FromRgb(10,38,32));b.FontWeight=FontWeights.SemiBold;}b.Click+=(s,e)=>{_selected=(string)((Button)s).Tag;BuildNav();RenderApps(true);_scroll.ScrollToTop();};_nav.Children.Add(b);}

    async void LoadCatalog(){_status.Text=L.T("loading",_settings.Language);var sw=Stopwatch.StartNew();_apps=await Task.Run(()=>_catalog.LoadFast(_settings));CatalogService.ApplySettings(_apps,_settings);Storage.SaveSettings(_settings);BuildNav();RenderQuick();RenderApps(true);_status.Text=string.Format(L.T("ready",_settings.Language),_apps.Count)+" · "+sw.ElapsedMilliseconds+" ms";var backgroundRefresh=Task.Run(()=>{var fresh=_catalog.Scan(_settings);Dispatcher.Invoke(()=>{if(Signature(fresh)!=Signature(_apps)){_apps=fresh;Storage.SaveSettings(_settings);BuildNav();RenderQuick();RenderApps(true);_status.Text=string.Format(L.T("ready",_settings.Language),_apps.Count);}});});}
    async void RefreshAsync(){_status.Text=L.T("loading",_settings.Language);_apps=await Task.Run(()=>_catalog.Scan(_settings));Storage.SaveSettings(_settings);BuildNav();RenderQuick();RenderApps(true);_status.Text=string.Format(L.T("ready",_settings.Language),_apps.Count);}
    static string Signature(IEnumerable<AppEntry> apps){return string.Join("\n",apps.OrderBy(x=>x.Id).Select(x=>x.Id+"|"+x.Path));}

    List<AppEntry> Visible(){var q=(_search==null?"":_search.Text).Trim();IEnumerable<AppEntry> list=_apps;if(_selected=="FAV")list=list.Where(a=>_settings.Favorites.Contains(a.Id));else if(_selected=="RECENT")list=list.Where(a=>_settings.Recent.Contains(a.Id));else if(_selected!="ALL")list=list.Where(a=>a.Category==_selected);if(q.Length>0)list=list.Where(a=>a.Name.IndexOf(q,StringComparison.CurrentCultureIgnoreCase)>=0);return list.OrderBy(a=>_selected=="RECENT"?_settings.Recent.IndexOf(a.Id):(_settings.Favorites.Contains(a.Id)?0:1)).ThenBy(a=>a.Name,StringComparer.CurrentCultureIgnoreCase).ToList();}
    void RenderApps(bool animate){if(_cards==null)return;if(_batch!=null)_batch.Stop();_cards.Children.Clear();_pending=Visible();_batchIndex=0;_title.Text=_selected=="ALL"?L.T("all",_settings.Language):_selected=="FAV"?L.T("fav",_settings.Language):_selected=="RECENT"?L.T("recent",_settings.Language):L.Category(_selected,_settings.Language);_count.Text=_pending.Count+" "+(L.En(_settings.Language)?"apps":"款软件");_empty.Text=L.T("empty",_settings.Language)+" · "+L.T("emptyhelp",_settings.Language);_empty.Visibility=_pending.Count==0?Visibility.Visible:Visibility.Collapsed;if(_pending.Count==0)return;
      _batch=new DispatcherTimer(DispatcherPriority.Background){Interval=TimeSpan.FromMilliseconds(18)};_batch.Tick+=(s,e)=>{for(int i=0;i<14&&_batchIndex<_pending.Count;i++,_batchIndex++){var card=MakeCard(_pending[_batchIndex]);_cards.Children.Add(card);if(animate&&!_settings.ReduceMotion)Reveal(card,Math.Min(_batchIndex,12)*12);}if(_batchIndex>=_pending.Count)_batch.Stop();};_batch.Start();}

    void RenderQuick(){if(_quick==null)return;_quick.Children.Clear();var chosen=_apps.Where(a=>_settings.Favorites.Contains(a.Id)).Concat(_apps).GroupBy(a=>a.Id).Select(g=>g.First()).Take(3).ToList();var width=Math.Max(230,(_content.ActualWidth>0?_content.ActualWidth:980)-24)/3;foreach(var app in chosen){var holder=new Grid{Width=width,Height=104,Margin=new Thickness(0,0,12,0),ClipToBounds=false};var b=TileButton(app,width,96,true);b.VerticalAlignment=VerticalAlignment.Bottom;b.MouseEnter+=(s,e)=>Panel.SetZIndex(holder,20);b.MouseLeave+=(s,e)=>Panel.SetZIndex(holder,0);holder.Children.Add(b);_quick.Children.Add(holder);}}

    FrameworkElement MakeCard(AppEntry app){
      var holder=new Grid{Width=184,Height=180,Margin=new Thickness(0,0,12,4),ClipToBounds=false,Opacity=1};var grid=new Grid{Width=184,Height=172,VerticalAlignment=VerticalAlignment.Bottom,ClipToBounds=false};var launch=TileButton(app,184,172,false);launch.MouseEnter+=(s,e)=>Panel.SetZIndex(holder,20);launch.MouseLeave+=(s,e)=>Panel.SetZIndex(holder,0);grid.Children.Add(launch);var fav=SmallButton(_settings.Favorites.Contains(app.Id)?L.T("favorited",_settings.Language):L.T("favorite",_settings.Language));fav.Width=L.En(_settings.Language)?58:48;fav.Height=26;fav.FontSize=10;fav.HorizontalAlignment=HorizontalAlignment.Right;fav.VerticalAlignment=VerticalAlignment.Top;fav.Margin=new Thickness(0,8,8,0);fav.ToolTip=_settings.Favorites.Contains(app.Id)?L.T("favorited",_settings.Language):L.T("favorite",_settings.Language);fav.Click+=(s,e)=>{ToggleFavorite(app);e.Handled=true;};Panel.SetZIndex(fav,2);grid.Children.Add(fav);holder.Children.Add(grid);
      var menu=new ContextMenu{Background=PanelBg,Foreground=TextMain};var folder=new MenuItem{Header=L.T("folder",_settings.Language)};folder.Click+=(s,e)=>OpenLocation(app);menu.Items.Add(folder);var move=new MenuItem{Header=L.T("move",_settings.Language)};foreach(var c in CatalogService.Categories){var item=new MenuItem{Header=L.Category(c,_settings.Language),IsCheckable=true,IsChecked=app.Category==c,Tag=c};item.Click+=(s,e)=>{app.Category=(string)((MenuItem)s).Tag;_settings.Categories[app.Id]=app.Category;Storage.SaveSettings(_settings);BuildNav();RenderApps(true);};move.Items.Add(item);}menu.Items.Add(move);launch.ContextMenu=menu;return holder;
    }

    Button TileButton(AppEntry app,double width,double height,bool quick){
      var button=new Button{Width=width,Height=height,Tag=app,Background=quick?new SolidColorBrush(Color.FromRgb(24,57,70)):CardBg,BorderBrush=new SolidColorBrush(Color.FromRgb(45,64,86)),BorderThickness=new Thickness(1),Foreground=TextMain,Padding=new Thickness(quick?16:12),Cursor=Cursors.Hand,HorizontalContentAlignment=HorizontalAlignment.Stretch};button.Template=RoundedButtonTemplate(14);var panel=new StackPanel{Orientation=quick?Orientation.Horizontal:Orientation.Vertical,VerticalAlignment=VerticalAlignment.Center};var icon=new Image{Width=quick?48:46,Height=quick?48:46,Margin=quick?new Thickness(0,0,14,0):new Thickness(0,0,0,11),Source=IconService.Get(app)};panel.Children.Add(icon);var texts=new StackPanel{VerticalAlignment=VerticalAlignment.Center};var n=Text(app.Name,quick?16:13,FontWeights.SemiBold,TextMain);n.TextAlignment=quick?TextAlignment.Left:TextAlignment.Center;n.TextTrimming=TextTrimming.CharacterEllipsis;n.MaxWidth=quick?165:140;texts.Children.Add(n);var c=Text(L.Category(app.Category,_settings.Language),10,FontWeights.Normal,TextMuted);c.TextAlignment=quick?TextAlignment.Left:TextAlignment.Center;c.Margin=new Thickness(0,6,0,0);texts.Children.Add(c);panel.Children.Add(texts);button.Content=panel;button.Click+=(s,e)=>Launch((AppEntry)((Button)s).Tag);button.MouseEnter+=(s,e)=>{button.Background=CardHover;Animate(button,1.025,-3,.16);};button.MouseLeave+=(s,e)=>{button.Background=quick?new SolidColorBrush(Color.FromRgb(24,57,70)):CardBg;Animate(button,1,0,.20);};button.PreviewMouseLeftButtonDown+=(s,e)=>Animate(button,.97,0,.08);return button;
    }

    void ToggleFavorite(AppEntry app){if(_settings.FavoriteKeys.Contains(app.StableKey))_settings.FavoriteKeys.Remove(app.StableKey);else _settings.FavoriteKeys.Add(app.StableKey);CatalogService.ApplySettings(_apps,_settings);Storage.SaveSettings(_settings);BuildNav();RenderQuick();RenderApps(false);}
    void Launch(AppEntry app){
      try{if(app.Target.StartsWith("shell:AppsFolder\\",StringComparison.OrdinalIgnoreCase))Process.Start(new ProcessStartInfo(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Windows),"explorer.exe"),app.Target){UseShellExecute=true});else Process.Start(new ProcessStartInfo(app.Path){UseShellExecute=true});_settings.Recent.Remove(app.Id);_settings.Recent.Insert(0,app.Id);if(_settings.Recent.Count>20)_settings.Recent.RemoveRange(20,_settings.Recent.Count-20);Storage.SaveSettings(_settings);BuildNav();_status.Text=string.Format(L.T("launched",_settings.Language),app.Name);}catch{_status.Text=L.T("failed",_settings.Language);}}
    void OpenLocation(AppEntry app){try{if(app.Target.StartsWith("shell:AppsFolder\\"))Process.Start("explorer.exe","shell:AppsFolder");else Process.Start("explorer.exe","/select,\""+app.Path+"\"");}catch{}}
    void OnKeys(object sender,KeyEventArgs e){if(e.Key==Key.F&&(Keyboard.Modifiers&ModifierKeys.Control)!=0){_search.Focus();_search.SelectAll();e.Handled=true;}else if(e.Key==Key.Escape)_search.Clear();else if(e.Key==Key.Enter&&_search.IsKeyboardFocusWithin){var one=Visible();if(one.Count==1)Launch(one[0]);}}

    TextBlock Text(string text,double size,FontWeight weight,Brush color){return new TextBlock{Text=text,FontFamily=new FontFamily("Microsoft YaHei UI, Segoe UI"),FontSize=size,FontWeight=weight,Foreground=color,TextTrimming=TextTrimming.CharacterEllipsis};}
    Button SmallButton(string text){var b=FlatButton(text,58,38);var normal=new SolidColorBrush(Color.FromRgb(22,35,53));var hover=new SolidColorBrush(Color.FromRgb(34,58,78));var border=new SolidColorBrush(Color.FromRgb(48,68,91));b.Margin=new Thickness(9,0,0,0);b.Background=normal;b.BorderBrush=border;b.BorderThickness=new Thickness(1);b.Template=RoundedButtonTemplate(10);b.MouseEnter+=(s,e)=>{b.Background=hover;b.BorderBrush=Mint;b.Foreground=TextMain;Animate(b,1.025,-1,.14);};b.MouseLeave+=(s,e)=>{b.Background=normal;b.BorderBrush=border;b.Foreground=TextMuted;Animate(b,1,0,.18);};return b;}
    Button FlatButton(string text,double width,double height){var b=new Button{Content=text,Width=width,Height=height,Background=Brushes.Transparent,Foreground=TextMuted,BorderThickness=new Thickness(0),FontFamily=new FontFamily("Microsoft YaHei UI, Segoe UI"),FontSize=12,Cursor=Cursors.Hand};b.MouseEnter+=(s,e)=>{if(((Button)s).Background==Brushes.Transparent)((Button)s).Background=new SolidColorBrush(Color.FromRgb(27,42,61));};b.MouseLeave+=(s,e)=>{var x=(Button)s;if(x.Tag!=null&&(string)x.Tag!=_selected)x.Background=Brushes.Transparent;};return b;}
    ControlTemplate RoundedButtonTemplate(double radius){var f=new FrameworkElementFactory(typeof(Border));f.SetValue(Border.CornerRadiusProperty,new CornerRadius(radius));f.SetBinding(Border.BackgroundProperty,new System.Windows.Data.Binding("Background"){RelativeSource=new System.Windows.Data.RelativeSource(System.Windows.Data.RelativeSourceMode.TemplatedParent)});f.SetBinding(Border.BorderBrushProperty,new System.Windows.Data.Binding("BorderBrush"){RelativeSource=new System.Windows.Data.RelativeSource(System.Windows.Data.RelativeSourceMode.TemplatedParent)});f.SetBinding(Border.BorderThicknessProperty,new System.Windows.Data.Binding("BorderThickness"){RelativeSource=new System.Windows.Data.RelativeSource(System.Windows.Data.RelativeSourceMode.TemplatedParent)});f.SetBinding(Border.PaddingProperty,new System.Windows.Data.Binding("Padding"){RelativeSource=new System.Windows.Data.RelativeSource(System.Windows.Data.RelativeSourceMode.TemplatedParent)});var p=new FrameworkElementFactory(typeof(ContentPresenter));p.SetBinding(ContentPresenter.HorizontalAlignmentProperty,new System.Windows.Data.Binding("HorizontalContentAlignment"){RelativeSource=new System.Windows.Data.RelativeSource(System.Windows.Data.RelativeSourceMode.TemplatedParent)});p.SetBinding(ContentPresenter.VerticalAlignmentProperty,new System.Windows.Data.Binding("VerticalContentAlignment"){RelativeSource=new System.Windows.Data.RelativeSource(System.Windows.Data.RelativeSourceMode.TemplatedParent)});f.AppendChild(p);return new ControlTemplate(typeof(Button)){VisualTree=f};}
    void Animate(UIElement element,double scale,double y,double seconds){if(_settings.ReduceMotion)return;var group=element.RenderTransform as TransformGroup;if(group==null){group=new TransformGroup();group.Children.Add(new ScaleTransform(1,1));group.Children.Add(new TranslateTransform());element.RenderTransform=group;element.RenderTransformOrigin=new Point(.5,.5);}var ease=new CubicEase{EasingMode=EasingMode.EaseOut};var a=new DoubleAnimation(scale,TimeSpan.FromSeconds(seconds)){EasingFunction=ease};((ScaleTransform)group.Children[0]).BeginAnimation(ScaleTransform.ScaleXProperty,a);((ScaleTransform)group.Children[0]).BeginAnimation(ScaleTransform.ScaleYProperty,a);((TranslateTransform)group.Children[1]).BeginAnimation(TranslateTransform.YProperty,new DoubleAnimation(y,TimeSpan.FromSeconds(seconds)){EasingFunction=ease});}
    void Reveal(UIElement e,int delay){e.Opacity=.25;var move=new TranslateTransform(0,8);e.RenderTransform=move;var d=TimeSpan.FromMilliseconds(delay);e.BeginAnimation(OpacityProperty,new DoubleAnimation(1,TimeSpan.FromMilliseconds(190)){BeginTime=d,EasingFunction=new CubicEase{EasingMode=EasingMode.EaseOut}});move.BeginAnimation(TranslateTransform.YProperty,new DoubleAnimation(0,TimeSpan.FromMilliseconds(220)){BeginTime=d,EasingFunction=new CubicEase{EasingMode=EasingMode.EaseOut}});}
    static T FindNameRecursive<T>(DependencyObject root,string name) where T:FrameworkElement{if(root==null)return null;var fe=root as FrameworkElement;if(fe!=null&&fe.Name==name)return (T)fe;for(int i=0;i<VisualTreeHelper.GetChildrenCount(root);i++){var found=FindNameRecursive<T>(VisualTreeHelper.GetChild(root,i),name);if(found!=null)return found;}return null;}
  }
}
